version: '3.8'

services:
  ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-learning-generator
    # ports:
    #   - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG=False
      - MAX_FILE_SIZE_MB=10
      - MAX_FLASHCARDS=20
      - MAX_MCQS=20
    volumes:
      # Mount for development (comment out in production)
      - ./app:/app/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    depends_on:
      - ai-agent
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
networks:
  default:
    name: ai-agent-network

    # docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMDI0MGMzYmI4M2QzY2U1ZTlhYjExNzU2YmRmZDlhMTQiLCJ0IjoiMjNjNmU3ZGUtNjNlYS00ZWU4LWFlOGUtMGY0ODY0YzkwMzE5IiwicyI6Ik5HWmpabVExWXpFdE4yUTJOQzAwWlRBeExXSXhaR1l0Tm1Oa05XTTBPREV4TXpSaCJ9